---
extends: "eslint:recommended"
rules:
  comma-dangle: [2, always-multiline]
  quotes: [2, single]
  no-unused-vars: [2, {vars: all, args: none}]
  no-console: [0]
  react/jsx-uses-vars: [2]
  react/jsx-uses-react: [2]
parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true

plugins:
  - react

env:
  es6: true
  browser: true
